version: '2'

services:

  mysql:
    build: ./db
    container_name: $MYSQL_HOST
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  nodejs:
    build: ./node
    container_name: nodejs
    environment:
      API_IP: $API_IP
      API_PORT: $API_PORT
      SERVER_APPLICATION_PORT: API_PORT
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./node:/home/node/app
      - ./node/node_modules:/home/node/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
