name: Run tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
        include:
          - os: ubuntu-20.04
          - os: ubuntu-18.04
          - os: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up docker
        uses: docker-practice/actions-setup-docker@master
      - name: Launch containers and run tests
        run: |
          sudo bash up.sh &
          sleep 120
          sudo docker exec nodejs 'npm' 'test'
